"""Intent labels (RAG Architecture §3.3.1)."""

INTENT_FACTUAL = "FACTUAL_LOOKUP"
INTENT_PROCESS = "PROCESS_HOWTO"
INTENT_PERFORMANCE = "PERFORMANCE_REQUEST"
INTENT_ADVISORY = "ADVISORY"
INTENT_COMPARISON = "COMPARISON"
INTENT_OUT_OF_SCOPE = "OUT_OF_SCOPE"

BLOCKED_INTENTS = frozenset({INTENT_ADVISORY, INTENT_COMPARISON, INTENT_OUT_OF_SCOPE})
